services:
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    environment:
      - LOG_DIRECTORY=/data/cowrie/logs
      - STATS_FILE=/data/stats/honeypot_stats.json
    volumes:
      - /home/e2506292/cowrie/var/log/cowrie:/data/cowrie/logs:ro
      - /var/lib/docker/vol/_data:/data/stats
      - /var/www/honeypot:/www
    ports:
      - "127.0.0.1:8000:8000"
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
    develop:
      watch:
        - action: rebuild
          path: ./web

volumes:
  stats_data:
    driver: local
  cowrie_logs:
    driver: local
  web_data:
    driver: local
